name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiY2ZhYmNjMTctMTRmMi00ZDlmLWFkY2MtZmM0MzlhMGRmYzgxIiwidGVuYW50X2lkIjoiM2YyODgzYjUzNmIyZDA2MDc2Y2NiOTc1MWQzOTU1MjJlODRkNGRlNGU5Y2RkYThmYmE5NTBmNGQ1N2NiNjlkZCIsImludGVybmFsX3NlY3JldCI6IjYxYTBhMzJmLWE5MTMtNDVkNS1iNDUzLTRlOGE3ZWE1MjA1MCJ9.46hWG7qu9X9u88jYp1d24iOkti6JXEL_hKgaxuCmS4g"

JWT_SECRET = "secret"

