name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDgyZTAxMTUtMmNkMy00YjRjLWExNmUtOWFlODU3NWRhMWQwIiwidGVuYW50X2lkIjoiM2YyODgzYjUzNmIyZDA2MDc2Y2NiOTc1MWQzOTU1MjJlODRkNGRlNGU5Y2RkYThmYmE5NTBmNGQ1N2NiNjlkZCIsImludGVybmFsX3NlY3JldCI6IjYxYTBhMzJmLWE5MTMtNDVkNS1iNDUzLTRlOGE3ZWE1MjA1MCJ9.PM7jXkTkY9UMom6X6Fts5cXM3v43JnB8Jr6gwuxwdfg"

JWT_SECRET = "secret"

